domain: lishuhang.me
url: https://lishuhang.me/2025
baseurl: "/2025"

title: 航通社
email: i@lishuhang.me
author: Shuhang Li

lang: zh

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
disqus:
  shortname: lishuhang

rrss:
  email: "i@lishuhang.me"
  telegram: "https://t.me/lishuhang"
  discord: "https://discord.com/"
