domain: lishuhang.me
url: https://lishuhang.me/2025
baseurl: "/2025"

title: AI Daily
email: i@lishuhang.me
author: Shuhang Li

lang: zh

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: " i@lishuhang.me"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
